### PR TITLE
Show Errors Inline via Linter Package

### PR DESCRIPTION
**Pull request by robwise**

### CODE REVIEW

**Comment by robwise** [comment]
@darahak or anyone else, can you help me beta test this for a little before we merge just to make sure I didn't miss an edge case or something?

**Comment by darahak** [comment]
@robwise I'll give it a try this weekend!

**Comment by robwise** [comment]
I've been using this for a while and I've noticed some obvious bugs that I somehow missed:

- strange linter error
- linter errors don't get cleared on reformatting

**Comment by robwise** [comment]
Okay, I addressed all issues, it seems to be working properly now!

**Comment by peterpme** [comment]
I was just thinking about this. You are awesome @robwise!

**Pull request merged**
