### PR TITLE
--arrow-parens is added as a configuration option

### LINKED ISSUE #340: Add configuration option for --arrow-parens
Currently, I cannot find the option in the settings to set value for --arrow-parens parameter.

We extend our Eslint ruleset from Airbnb and arrow-parens rule complains always after the prettier formats the code.

Please add the option to the settings.

### PR DESCRIPTION
**Pull request by ferdibiflator**
fix #340

### CODE REVIEW

**Comment by robwise** [comment]
@ferdibiflator thanks for the PR! Could you please amend the commit message so that it will show up in our auto-generated changelog? Something like `feat(options): add arrow-parens prettier option` (or something). Then I can merge!

**Comment by darahak** [comment]
@robwise Not related to this PR, but should the test snapshot look like [this](https://github.com/prettier/prettier-atom/blob/master/src/atomInterface/__snapshots__/index.test.js.snap)? I would expect anything but `undefined`.

**Comment by ferdibiflator** [comment]
@robwise it's ready!

**Comment by robwise** [comment]
@darahak yeah that looks like a mistake, added an issue here: https://github.com/prettier/prettier-atom/issues/342

**Comment by mauricecruz** [comment]
Should there be support for the `"as-needed"` option? We use the airbnb inspired version and this is kinda throwing a wrench in the autofixing
https://eslint.org/docs/rules/arrow-parens#further-reading

**Comment by robwise** [comment]
@mauricecruz we'd need support from prettier to allow doing this, this package is just the bridge between Atom and prettier. In the meantime, if it matters a lot, you could try using the prettier-eslint integration (although there's a bug right now in #334) which will call eslint --fix after running prettier to ensure conformance with your eslint rules.

**Pull request merged**
