### PR TITLE
feat(deps): upgrade to latest prettier(-eslint)

### PR DESCRIPTION
**Pull request by kentcdodds**

### CODE REVIEW

**Comment by aaronshaf** [comment]
🚢 :shipit:

**Comment by robwise** [comment]
@kentcdodds Thanks! Could you also update the `yarn.lock` real quick and then I'll merge?

**Comment by kentcdodds** [comment]
I'm away from the keyboard and won't be able to update for a while. Feel free to close this and do it yourself when you're ready to publish 😀

**Comment by robwise** [comment]
roger that, doing it now!

**Comment by robwise** [comment]
actually I will just amend I guess

**Pull request closed without merging**
